/*
 * This source file was generated by the Gradle 'init' task
 */
package com.ssnagin.lab5java.sem2.lab5;

import com.ssnagin.lab5java.sem2.lab5.model.Album;
import com.ssnagin.lab5java.sem2.lab5.model.Coordinates;
import com.ssnagin.lab5java.sem2.lab5.model.MusicBand;
import com.ssnagin.lab5java.sem2.lab5.model.MusicGenre;
import java.time.LocalDate;

public class App {
    public static void main(String[] args) {
        MusicBand musicBand = new MusicBand(
                1,
                "test", 
                new Coordinates((long) 228, 1),
                LocalDate.now(),
                1L, 
                1,
                MusicGenre.MATH_ROCK,
                new Album("Test", (long) 123)
        );
    }
}
